sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpangocairo-1.0-0 libcairo2-dev libgnomeui-dev libgstreamer0.10-dev libglib2.0-dev libjpeg-dev libgif-dev

language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
